[package]
name = "wikipedia-mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.12.0"
petgraph = "0.5.1"
dot = "0.1.4"
graphviz-rust = "0.9.0"
anyhow = "1.0.82"
